fix 42

diff --git a/.github/workflows/allure-junit.yml b/.github/workflows/allure-junit.yml
--- a/.github/workflows/allure-junit.yml
+++ b/.github/workflows/allure-junit.yml
@@ -50,18 +50,18 @@ jobs:
 
       - name: Run Chrome with debug flags
         run: |
-          mkdir -p /tmp/chrome-logs
-          export CHROME_LOG_FILE=/tmp/chrome-logs/chrome.log
-          /usr/bin/google-chrome --headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 > $CHROME_LOG_FILE 2>&1 &
-          sleep 10
-          cat $CHROME_LOG_FILE
+            mkdir -p /tmp/chrome-logs
+            export CHROME_LOG_FILE=/tmp/chrome-logs/chrome.log
+            /usr/bin/google-chrome --headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 > $CHROME_LOG_FILE 2>&1 &
+            sleep 10
+            cat $CHROME_LOG_FILE
 
       - name: Run tests
         run: |
-          mkdir -p /tmp/chromedriver-logs
-          export CHROMEDRIVER_LOG_FILE=/tmp/chromedriver-logs/chromedriver.log
-          mvn clean test -Dchrome.headless=true -Dwebdriver.chrome.logfile=$CHROMEDRIVER_LOG_FILE
-          cat $CHROMEDRIVER_LOG_FILE
+                mkdir -p /tmp/chromedriver-logs
+                mvn clean test -Dchrome.headless=true -Dwebdriver.chrome.logfile=/tmp/chromedriver-logs/chromedriver.log
+                cat /tmp/chromedriver-logs/chromedriver.log || echo "ChromeDriver log file not found"
+            
 
       - name: Load test report history
         uses: actions/checkout@v4
